apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: certificate-policy-console-ingress
        spec:
          remediationAction: inform
          severity: high
          minimumDuration: 720h
          namespaceSelector:
            include: ["openshift-console", "openshift-ingress"]
          evaluationInterval:
            compliant: 10m
            noncompliant: 30s
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  # Note: If "placementRef: Required value, subjects: Required value" error persists,
  # clean up resources and verify CRDs:
  # oc delete policy certificate-policy-console-ingress -n policies-deploy
  # oc delete placementrule placement-certificate-policy-console-ingress -n policies-deploy
  # oc get crd placementbindings.policy.open-cluster-management.io -o yaml
  subjects:
    - name: certificate-policy-console-ingress
      kind: Policy
      apiGroup: policy.open-cluster-management.io
  placementRef:
    name: placement-certificate-policy-console-ingress
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions: []