apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: certificate-policy-console-ingress
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            include: ["openshift-console", "openshift-ingress"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: kubernetes.io/tls
                metadata:
                  namespace: "{{ fromClusterClaim `name` }}"
                data:
                  # Placeholder base64-encoded value for tls.crt (decodes to "tls-crt-placeholder")
                  # Note: This monitors Secret existence, not certificate expiration. Use CertificatePolicy for expiration checks.
                  tls.crt: dGxzLWNydC1wbGFjZWhvbGRlcg==
          evaluationInterval:
            compliant: 10m
            noncompliant: 30s
          pruneObjectBehavior: DeleteIfCreated
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  subjects:
    - name: certificate-policy-console-ingress
      kind: Policy
      apiGroup: policy.open-cluster-management.io
  placementRef:
    name: placement-certificate-policy-console-ingress
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions: []