apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: certificate-policy-console-ingress
        spec:
          remediationAction: inform
          severity: high
          minimumDuration: 720h
          namespaceSelector:
            include: ["openshift-console", "openshift-ingress"]
          evaluationInterval:
            compliant: 10m
            noncompliant: 30s
---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicySet
metadata:
  name: certificate-policy-console-ingress-set
  namespace: policies-deploy
spec:
  description: PolicySet for certificate expiration monitoring
  policies:
    - certificate-policy-console-ingress
---
apiVersion: cluster.open-cluster-management.io/v1
kind: Placement
metadata:
  name: placement-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-certificate-policy-console-ingress
  namespace: policies-deploy
spec:
  subjects:
    - name: certificate-policy-console-ingress-set
      kind: PolicySet
      apiGroup: policy.open-cluster-management.io
  placementRef:
    name: placement-certificate-policy-console-ingress
    kind: Placement
    apiGroup: cluster.open-cluster-management.io