apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: '2022-04-20T06:46:24Z'
  generation: 1
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
      time: '2022-04-20T06:46:24Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/openshift-gitops-operator.openshift-operators': {}
      manager: olm
      operation: Update
      time: '2022-04-20T06:46:24Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
      time: '2022-04-20T06:46:48Z'
  name: openshift-gitops-operator
  namespace: openshift-operators
  resourceVersion: '12070300'
  uid: ee03a437-f688-4c63-be76-55975a07a3ff
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: do480-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.4.2
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-ff4zn
    uuid: 761d2f2d-b58a-43c5-9a54-4ef95e1860a3
  lastUpdated: '2022-04-26T11:43:44Z'
  installedCSV: openshift-gitops-operator.v1.4.2
  currentCSV: openshift-gitops-operator.v1.4.2
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-ff4zn
    namespace: openshift-operators
    resourceVersion: '3118672'
    uid: 761d2f2d-b58a-43c5-9a54-4ef95e1860a3
  state: AtLatestKnown
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: do480-catalog
        namespace: openshift-marketplace
        resourceVersion: '3059178'
        uid: 1adb1160-1120-4521-8011-e4a34616cbb6
      healthy: true
      lastUpdated: '2022-04-20T06:46:24Z'
  conditions:
    - lastTransitionTime: '2022-04-20T06:46:24Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
    - status: 'False'
      type: ResolutionFailed
  installPlanGeneration: 1

