apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
- applications.yaml
- deployment-frontend.yaml
- deployment.yaml
- service.yaml
- service-frontend.yaml
- namespace.yaml
- placementrule.yaml
- route.yaml
