apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-persistent-template
    application: finance-application-2
    name: mysql-finance-application-2
    template: mysql-persistent-template
  name: mysql-finance-application-2
  namespace: company-applications-5
spec:
  clusterIP: 172.30.90.194
  clusterIPs:
  - 172.30.90.194
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
  selector:
    app: mysql-finance-application-2
