apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-23T10:42:34Z"
  labels:
    app: mysql-persistent-template
    application: finance-application-2
    name: mysql-finance-application-2
    template: mysql-persistent-template
  name: mysql-finance-application-2
  namespace: company-applications-5
  resourceVersion: "3604906"
  uid: 52544b2c-78a1-4acf-878a-4febd4b21d7f
spec:
  clusterIP: 172.30.90.194
  clusterIPs:
  - 172.30.90.194
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-finance-application-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
