apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
  creationTimestamp: "2021-12-23T10:42:34Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mysql-persistent-template
    application: finance-application-2
    template: mysql-persistent-template
  name: dbclaim
  namespace: company-applications-5
  resourceVersion: "3604923"
  uid: e60375d3-2539-495c-8b41-6bc581dda1fd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-storage
  volumeMode: Filesystem
  volumeName: pvc-e60375d3-2539-495c-8b41-6bc581dda1fd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  phase: Bound
