---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mysql-development-subscription
  labels:
    app: mysql
  annotations:
    apps.open-cluster-management.io/github-path: mysql
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: application/gitops
  placement:
    placementRef:
      name: mysql-development
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mysql-production-subscription
  namespace: mysql
  labels:
    app: mysql
  annotations:
    apps.open-cluster-management.io/github-path: mysql
    apps.open-cluster-management.io/github-branch: production
spec:
  channel: application/gitops
  placement:
    placementRef:
      name: mysql-production
      kind: PlacementRule
