
---
#
#       |`o``\  ,     
#       |_|-/ \_|__   
#     _/..\-.\|   |   
#______\""/`````(o)___
- name: Login to OpenShift cluster 
  shell:
    cmd: oc login -u admin -p redhat {{ hub_cluster_host }} 
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    


- name: Delete Observability 
  k8s:
    api_version: observability.open-cluster-management.io/v1beta2
    kind: MultiClusterObservability
    name: "observability"
    state: absent


