apiVersion: apps/v1
kind: Deployment
metadata:
  name: roster
spec:
  template:
    spec:
      containers:
        - name: do280-roster
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3